; /etc/supervisor/conf.d/avatar-queue.conf
[program:avatar-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/avatar/current/artisan queue:work redis --queue=default --sleep=1 --tries=2 --timeout=120 --max-time=3600
directory=/var/www/avatar/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/avatar-queue.log
stopwaitsecs=3600
